[build]
builder = "nixpacks"
buildCommand = "pip install -e ."

[deploy]
startCommand = "python scripts/railway_ingest.py"
restartPolicyType = "on_failure"

[cron]
schedule = "*/10 * * * *"
command = "python scripts/railway_ingest.py" 